ARG IMAGE=arm64v8/python:3.11-slim
FROM ${IMAGE}

RUN apt-get update && \
    apt-get install -y build-essential && \
    pip install --upgrade pip

WORKDIR /app
COPY . .

RUN pip install poetry
RUN poetry install
RUN pip install pyinstaller

RUN pyinstaller --onefile submitr/scripts/submitr.py

RUN chmod a+x dist/submitr
CMD ["./dist/submitr"]
