ARG IMAGE=
FROM ${IMAGE}

RUN /bin/bash -c "\
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*"
RUN yum install sudo -y
RUN sudo yum install git python3 gcc make bzip2 zlib-devel readline-devel sqlite-devel openssl-devel tk-devel libffi-devel wget xz-devel -y

WORKDIR /app
COPY . .

RUN curl https://pyenv.run | /bin/bash
RUN export PYENV_ROOT="$HOME/.pyenv" ; \
    export PATH="$PYENV_ROOT/bin:$PATH" ; \
    eval "$(pyenv init -)" ; \
    eval "$(pyenv virtualenv-init -)" ; \
    pyenv install 3.11.8 ; \
    pyenv virtualenv 3.11.8 submitr-3.11 ; \
    pyenv activate submitr-3.11 ; \
    make build ; \
    pip install pyinstaller ; \
    pyinstaller --onefile submitr/scripts/submitr.py

RUN chmod a+x dist/submitr
CMD ["./dist/submitr"]
