# Use an official Python runtime as a parent image
# Nevermind ARM for now; does not work.
ARG IMAGE=python:3.9-slim
FROM ${IMAGE}


# Install system dependencies and PyInstaller
RUN apt-get update && \
    apt-get install -y build-essential && \
    pip install --upgrade pip

# Create a working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install Poetry
RUN pip install poetry

# Install project dependencies
RUN poetry install

# Install project dependencies
RUN pip install pyinstaller

# Run PyInstaller to build the executable
RUN pyinstaller --onefile submitr/scripts/submitr.py
RUN chmod a+x dist/submitr

# Define the entry point for the container (optional, for testing purposes)
CMD ["./dist/submitr"]
