# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Install system dependencies and PyInstaller
RUN apt-get update && \
    apt-get install -y build-essential && \
    pip install --upgrade pip

# Create a working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install Poetry
RUN pip install poetry

# Install project dependencies
RUN poetry install

# Install project dependencies
RUN pip install pyinstaller

# Run PyInstaller to build the executable
RUN pyinstaller --onefile submitr/scripts/submitr.py

# Define the entry point for the container (optional, for testing purposes)
CMD ["./dist/submitr"]
