FROM davidmichaels/harvard:linux-x86-centos-python-3.11

USER root
WORKDIR /app
COPY . .

RUN source ~/.bashrc ; \
    make build ; \
    pip install distutils pyinstaller ; \
    pyinstaller --onefile submitr/scripts/submitr.py

RUN chmod a+x dist/submitr
CMD ["./dist/submitr"]
