name: BINARY RELEASE

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  release:
    runs-on: macos-13

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Sanity Checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name=${{ github.ref_name }}
          if [[ $GITHUB_REF =~ ^refs/tags/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            if [ -f "binaries/submitr-macos.${tag_name}" ] && \
               [ -f "binaries/submitr-linux-x86.${tag_name}" ] && \
               [ -f "binaries/submitr-linux-arm.${tag_name}" ]; then
              echo "Releasing binary artifacts for tag: ${tag_name} ..."
            else
              echo "Latest binary artifacts not all built. No action taken."
              exit 1
            fi
          else
            echo "Release is not a non-beta. No action taken."
            exit 1
          fi

      - name: Create Binaries
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        run: |
          echo "Installing docker."
          HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
          echo "Installing colima."
          brew install colima
          echo "Starting colima."
          colima start
          echo "Waiting for docker get up/running. This can take over 2 minutes ..."
          while (! docker stats --no-stream ); do
            echo "Waiting for docker to start ..."
            sleep 3
          done
          echo "Docker now seems to be up/running."
          echo "Building smaht-submitr binaries."
          make exe
          echo "Done building smaht-submitr binaries."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Binaries Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Binaries to Release
        run: |
          tag_name=${{ github.ref_name }}
          echo "Releasing binary artifacts for tag: ${tag_name}"
          gh release upload ${{ github.ref_name }} binaries/submitr-macos --clobber
          gh release upload ${{ github.ref_name }} binaries/submitr-linux-x86 --clobber
          gh release upload ${{ github.ref_name }} binaries/submitr-linux-arm --clobber
          echo "Done releasing binary artifacts for tag: ${tag_name}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
