name: BINARIES RELEASE

permissions:
  contents: write

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "Tag Name: ${{ steps.create_release.outputs.tag_name }}"
            for file in $(find binaries -type f ! -name "submitr-${{ github.ref_name }}.zip"); do
              echo "Uploading $file"
              gh release upload ${{ github.ref_name }} "$file" --clobber
            done
          else
            echo "Did not meet release criteria. No action taken."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
