name: BINARY RELEASE

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  release:
    runs-on: macos-13

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Sanity Checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name=${{ github.ref_name }}
          if [[ $GITHUB_REF =~ ^refs/tags/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            if [ -f "binaries/submitr-macos.${tag_name}" ] && \
               [ -f "binaries/submitr-linux-x86.${tag_name}" ] && \
               [ -f "binaries/submitr-linux-arm.${tag_name}" ]; then
              echo "Releasing binary artifacts for tag: ${tag_name} ..."
            else
              echo "Latest binary artifacts not all built. No action taken."
              exit 1
            fi
          else
            echo "Release is not a non-beta. No action taken."
            exit 1
          fi

      - name: Upload Release Assets
        run: |
          echo "Building MacOS binaries."
          make exe-macos
          echo "Done building MacOS binaries."
#         echo "Installing docker for building Linux binaries."
#         HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
#         echo "Installing colima for running docker."
#         brew install colima
#         echo "Starting docker via colima."
#         colima start
#         echo "Waiting for docker come up."
#         while (! docker stats --no-stream ); do
#           sleep 3
#         done
#         echo "Docker is up/running."
#         echo "Building Linux binaries."
#         make exe-linux
#         echo "Done building Linux binaries."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
