name: BINARIES RELEASE

permissions:
  contents: write

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            if [ -f "binaries/submitr-macos.0.8.13" ] && \
               [ -f "binaries/submitr-linux-x86.0.8.13" ] && \
               [ -f "binaries/submitr-linux-arm.0.8.13" ]; then
              echo "Releasing binaries for tag: ${{ steps.create_release.outputs.tag_name }}"
              gh release upload ${{github.ref_name}} binaries/submitr-macos --clobber
              gh release upload ${{github.ref_name}} binaries/submitr-linux-x86 --clobber
              gh release upload ${{github.ref_name}} binaries/submitr-linux-arm --clobber
            else
              echo "Latest binary artifacts not all built. No action taken."
            fi
          else
            echo "Release is not a non-beta. No action taken."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
