name: BINARY RELEASE

permissions:
  contents: write

on:
# push:
#   branches: [ pyinstaller-experiment-20240611 ]
  push:
    # Only run this workflow to create binaries when a non-beta tag is created.
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:

  build-macos-x86:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Build MacOS Binary
        run: |
          echo "Building MacOS binaries."
          make exe-macos
          mv -f binaries/submitr-macos binaries/submitr-macos-x86
          echo "Done building MacOS binaries."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload MacOS Binary (x86) Artifact
        uses: actions/upload-artifact@v3
        with:
          name: submitr-macos-x86
          path: binaries/submitr-macos-x86

  build-macos-arm:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Build MacOS Binary
        run: |
          echo "Building MacOS binaries."
          make exe-macos
          mv -f binaries/submitr-macos binaries/submitr-macos-arm
          echo "Done building MacOS binaries."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload MacOS Binary (arm) Artifact
        uses: actions/upload-artifact@v3
        with:
          name: submitr-macos-arm
          path: binaries/submitr-macos-arm

  build-linux-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Linux Binary (x86)
        run: |
          echo "Building Linux binary (x86)."
          make exe-linux-x86
          echo "Done building Linux binary (x86)."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux Binary (x86) Artifact
        uses: actions/upload-artifact@v3
        with:
          name: submitr-linux-x86
          path: binaries/submitr-linux-x86

  build-linux-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v2

      - name: Build Linux Binary (arm)
        run: |
          echo "Building Linux binary (arm)."
          make exe-linux-arm
          echo "Done building Linux binary (arm)."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux Binary (arm) Artifact
        uses: actions/upload-artifact@v3
        with:
          name: submitr-linux-arm
          path: binaries/submitr-linux-arm

  create-release:
    runs-on: ubuntu-latest
    needs: [build-macos-x86, build-macos-arm, build-linux-x86, build-linux-arm]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download MacOS Binary (x86) Artifact
        uses: actions/download-artifact@v3
        with:
          name: submitr-macos-x86

      - name: Download MacOS Binary (arm) Artifact
        uses: actions/download-artifact@v3
        with:
          name: submitr-macos-arm

      - name: Download Linux Binary (x86) Artifact
        uses: actions/download-artifact@v3
        with:
          name: submitr-linux-x86

      - name: Download Linux Binary (arm) Artifact
        uses: actions/download-artifact@v3
        with:
          name: submitr-linux-arm

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v1.0.0'  # Adjust the tag name as needed
          release_name: 'Release v1.0.0'
          draft: false
          prerelease: false

      - name: Upload MacOS Binary (x86) to GitHub Release
        run: |
          gh release upload ${{ github.ref_name }} submitr-macos-x86 --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload MacOS Binary (arm) to GitHub Release
        run: |
          gh release upload ${{ github.ref_name }} submitr-macos-arm --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux Binary (x86) to GitHub Release
        run: |
          gh release upload ${{ github.ref_name }} submitr-linux-x86 --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux Binary (arm) to GitHub Release
        run: |
          gh release upload ${{ github.ref_name }} submitr-linux-arm --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
