
# Docs Deployment for submitr 

name: deploy-docs

# Controls when the action will run.
on:
  # All non-beta tag pushes.
  push:
    tags:
      - 'v*'
    except:
      - 'v*b*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Docs
        env:
          DOCS_TOKEN: ${{ secrets.DOCS_TOKEN }}
        run: curl -X POST -d "ref=master" -d "token=$DOCS_TOKEN" https://readthedocs.org/api/v2/webhook/submitr/246175/
