name: BINARY RELEASE TEST

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
# push:
#   # Only run this workflow to create binaries when a non-beta tag is created.
#   tags:
#     - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:

  build-macos-x86:
    runs-on: macos-13
    steps:
      - name: Test MacOS Binary (x86)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "GitHub runner info:" `uname -a`
          echo "Smoke testing MacOS binary (x86)"
          echo "Installing MacOS binary (x86):" ${{ github.event.release.tag_name }}
          echo "debug2a"
          curl -H "Authorization: token ${GITHUB_TOKEN}" https://raw.githubusercontent.com/smaht-dac/submitr/pyinstaller-experiment-20240611/install.sh
          echo "debug3a"
          # This GITHUB_TOKEN thing is ONLY to make this work consistently
          # from this workflow; users to NOT need to do anything like this.
          curl -H "Authorization: token ${GITHUB_TOKEN}" https://raw.githubusercontent.com/smaht-dac/submitr/pyinstaller-experiment-20240611/install.sh | /bin/bash
          echo "Running smaht-submitr version. Should be the same as what was mentioned above."
          actual_version=`./submitr version`
          echo "smaht-submitr version:" ${actual_version}
          file ./submitr
          echo "Done smoke testing MacOS binary (x86)"

  build-macos-arm:
    runs-on: macos-14
    steps:
      - name: Test MacOS Binary (arm)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "GitHub runner info:" `uname -a`
          expected_version=${{ github.event.release.tag_name }}
          echo "Smoke testing MacOS binary (arm)"
          echo "debug1"
          which /bin/bash
          echo "debug2"
          curl -H "Authorization: token ${GITHUB_TOKEN}" https://raw.githubusercontent.com/smaht-dac/submitr/pyinstaller-experiment-20240611/install.sh
          echo "debug3"
          echo "Installing MacOS binary (arm):" ${{ github.event.release.tag_name }}
          curl -H "Authorization: token ${GITHUB_TOKEN}" https://raw.githubusercontent.com/smaht-dac/submitr/pyinstaller-experiment-20240611/install.sh | /bin/bash
          echo "Running smaht-submitr version. Should be the same as what was mentioned above."
          actual_version=`./submitr version`
          echo "smaht-submitr version:" ${actual_version}
          file ./submitr
          echo "Done smoke testing MacOS binary (arm)"

  build-linux-x86:
    runs-on: ubuntu-latest
    steps:
      - name: Test Linux Binary (x86)
        run: |
          echo "GitHub runner info:" `uname -a`
          expected_version=${{ github.event.release.tag_name }}
          echo "Smoke testing Linux binary (x86)"
          echo "Installing Linux binary (x86):" ${{ github.event.release.tag_name }}
          curl https://raw.githubusercontent.com/smaht-dac/submitr/pyinstaller-experiment-20240611/install.sh | /bin/bash
          echo "Running smaht-submitr version. Should be the same as what was mentioned above."
          actual_version=`./submitr version`
          echo "smaht-submitr version:" ${actual_version}
          file ./submitr
          echo "Done smoke testing Linux binary (x86)"

  build-linux-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - name: Build Linux Binary (arm)
        run: |
          echo "GitHub runner info:" `uname -a`
          expected_version=${{ github.event.release.tag_name }}
          echo "Smoke testing Linux binary (arm)"
          echo "Installing Linux binary (arm):" ${{ github.event.release.tag_name }}
          curl https://raw.githubusercontent.com/smaht-dac/submitr/pyinstaller-experiment-20240611/install.sh | /bin/bash
          echo "Running smaht-submitr version. Should be the same as what was mentioned above."
          actual_version=`./submitr version`
          echo "smaht-submitr version:" ${actual_version}
          file ./submitr
          echo "Done smoke testing Linux binary (arm)"
