name: BINARY RELEASE

permissions:
  contents: write

on:
  push:
    branches: [ post-pyinstaller-20240625 ]
  pull_request:
    branches: [ post-pyinstaller-20240625 ]
  push:
    # Only run this workflow to create binaries when a non-beta tag is created.
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-macos-x86:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Build MacOS Binary (x86)
        run: |
          echo "GitHub runner info:"
          uname -a
          echo "Building MacOS binary (x86)."
          make exe-macos
          mv -f binaries/submitr-macos binaries/submitr-macos-x86
          echo "Done building MacOS binary (x86). Info below:"
          ls -l binaries/submitr-macos-x86
          file binaries/submitr-macos-x86
          echo smaht-submitr version: `binaries/submitr-macos-x86 version`
      - name: Upload MacOS Binary (x86) Artifact
        uses: actions/upload-artifact@v3
        with:
          name: submitr-macos-x86
          path: binaries/submitr-macos-x86

  build-macos-arm:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Build MacOS Binary (arm)
        run: |
          echo "GitHub runner info:"
          uname -a
          echo "Building MacOS binary (arm)."
          make exe-macos
          mv -f binaries/submitr-macos binaries/submitr-macos-arm
          echo "Done building MacOS binary (arm). Info below:"
          ls -l binaries/submitr-macos-arm
          file binaries/submitr-macos-arm
          echo smaht-submitr version: `binaries/submitr-macos-arm version`
      - name: Upload MacOS Binary (arm) Artifact
        uses: actions/upload-artifact@v3
        with:
          name: submitr-macos-arm
          path: binaries/submitr-macos-arm

  build-linux-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Linux Binary (x86)
        run: |
          echo "GitHub runner info:"
          uname -a
          echo "Building Linux binary (x86)."
          make exe-linux-x86
          echo "Done building Linux binary (x86). Info below:"
          ls -l binaries/submitr-linux-x86
          file binaries/submitr-linux-x86
          echo smaht-submitr version: `binaries/submitr-linux-x86 version`
      - name: Upload Linux Binary (x86) Artifact
        uses: actions/upload-artifact@v3
        with:
          name: submitr-linux-x86
          path: binaries/submitr-linux-x86

  build-linux-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v2
      - name: Build Linux Binary (arm)
        run: |
          echo "GitHub runner info:"
          uname -a
          echo "Building Linux binary (arm)."
          make exe-linux-arm
          echo "Done building Linux binary (arm). Info below:"
          ls -l binaries/submitr-linux-arm
          file binaries/submitr-linux-arm
          echo smaht-submitr version: `binaries/submitr-linux-arm version`
      - name: Upload Linux Binary (arm) Artifact
        uses: actions/upload-artifact@v3
        with:
          name: submitr-linux-arm
          path: binaries/submitr-linux-arm

  create-release:
    runs-on: ubuntu-latest
    needs: [build-macos-x86, build-macos-arm, build-linux-x86, build-linux-arm]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download MacOS Binary (x86) Artifact
        uses: actions/download-artifact@v3
        with:
          name: submitr-macos-x86

      - name: Download MacOS Binary (arm) Artifact
        uses: actions/download-artifact@v3
        with:
          name: submitr-macos-arm

      - name: Download Linux Binary (x86) Artifact
        uses: actions/download-artifact@v3
        with:
          name: submitr-linux-x86

      - name: Download Linux Binary (arm) Artifact
        uses: actions/download-artifact@v3
        with:
          name: submitr-linux-arm

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}  # Adjust the tag name as needed
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload MacOS Binary (x86) to GitHub Release
        run: |
          gh release upload ${{ github.ref_name }} submitr-macos-x86 --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload MacOS Binary (arm) to GitHub Release
        run: |
          gh release upload ${{ github.ref_name }} submitr-macos-arm --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux Binary (x86) to GitHub Release
        run: |
          gh release upload ${{ github.ref_name }} submitr-linux-x86 --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux Binary (arm) to GitHub Release
        run: |
          gh release upload ${{ github.ref_name }} submitr-linux-arm --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
