name: BINARY RELEASE TEST

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
# push:
#   # Only run this workflow to create binaries when a non-beta tag is created.
#   tags:
#     - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:

  build-macos-x86:
    runs-on: macos-13
    steps:
      - name: Test MacOS Binary (x86)
        run: |
          echo "GitHub runner info:" `uname -a`
          expected_version=${{ github.event.release.tag_name }}
          echo "Smoke testing MacOS binary (x86)"
          echo "Installing MacOS binary (x86): ${expected_version}"
          # For some reason on MacOS the curl intermittently fails if we do it immediately, so we take a breath.
          sleep 3
          curl https://raw.githubusercontent.com/smaht-dac/submitr/pyinstaller-experiment-20240611/install.sh | /bin/bash
          echo "Running submitr version. Should be the same as what was mentioned above."
          ./submitr version
          echo "Done smoke testing MacOS binary (x86)"

  build-macos-arm:
    runs-on: macos-14
    steps:
      - name: Test MacOS Binary (arm)
        run: |
          echo "GitHub runner info:" `uname -a`
          expected_version=${{ github.event.release.tag_name }}
          echo "Smoke testing MacOS binary (arm)"
          echo "Installing MacOS binary (arm): ${expected_version}"
          # For some reason on MacOS the curl intermittently fails if we do it immediately, so we take a breath.
          sleep 3
          curl https://raw.githubusercontent.com/smaht-dac/submitr/pyinstaller-experiment-20240611/install.sh | /bin/bash
          echo "Running submitr version. Should be the same as what was mentioned above."
          ./submitr version
          echo "Done smoke testing MacOS binary (arm)"

  build-linux-x86:
    runs-on: ubuntu-latest
    steps:
      - name: Test Linux Binary (x86)
        run: |
          echo "GitHub runner info:" `uname -a`
          expected_version=${{ github.event.release.tag_name }}
          echo "Smoke testing Linux binary (x86)"
          echo "Installing Linux binary (x86): ${expected_version}"
          curl https://raw.githubusercontent.com/smaht-dac/submitr/pyinstaller-experiment-20240611/install.sh | /bin/bash
          echo "Running submitr version. Should be the same as what was mentioned above."
          ./submitr version
          echo "Done running submitr version."
          echo "Done smoke testing Linux binary (x86)"

  build-linux-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - name: Build Linux Binary (arm)
        run: |
          echo "GitHub runner info:" `uname -a`
          expected_version=${{ github.event.release.tag_name }}
          echo "Smoke testing Linux binary (arm)"
          echo "Installing Linux binary (arm): ${expected_version}"
          curl https://raw.githubusercontent.com/smaht-dac/submitr/pyinstaller-experiment-20240611/install.sh | /bin/bash
          echo "Running submitr version. Should be the same as what was mentioned above."
          actual_version=`./submitr version`
          echo ${actual_version}
          echo "Done smoke testing Linux binary (arm)"
